import { Role } from "@prisma/client";
import { redirect } from "next/navigation";
import { getSession } from "@/lib/auth";
import { db } from "@/lib/db";
import { AreaForm, CodRuleForm, RateCardForm, ZoneForm } from "@/components/config-forms";

export default async function AdminPage() {
  const session = await getSession(); if (!session) redirect("/login"); if (session.role !== Role.ADMIN) redirect("/dashboard");
  const [zones, rates, codRules, agents] = await Promise.all([
    db.zone.findMany({ include: { areas: true }, orderBy: { name: "asc" } }),
    db.rateCard.findMany({ include: { originZone: true, destinationZone: true }, orderBy: { updatedAt: "desc" } }),
    db.codRule.findMany({ orderBy: { orderType: "asc" } }),
    db.agentProfile.findMany({ include: { user: true, zone: true }, orderBy: { user: { name: "asc" } } }),
  ]);
  return <><div className="page-title"><div><h1>Network configuration</h1><p>Pricing and serviceability live here—never hardcoded.</p></div></div><div className="stats-grid"><div className="stat-card"><div className="stat-label">Zones</div><div className="stat-value">{zones.length}</div><div className="stat-note">{zones.reduce((sum, zone) => sum + zone.areas.length, 0)} service areas</div></div><div className="stat-card"><div className="stat-label">Rate cards</div><div className="stat-value">{rates.length}</div><div className="stat-note">B2B and B2C routes</div></div><div className="stat-card"><div className="stat-label">COD rules</div><div className="stat-value">{codRules.length}</div><div className="stat-note">Order-type specific</div></div><div className="stat-card"><div className="stat-label">Agents</div><div className="stat-value">{agents.length}</div><div className="stat-note">{agents.filter((agent) => agent.available).length} available</div></div></div><div className="two-col"><div className="form"><section className="card"><div className="card-head"><h2>Rate cards</h2><span className="subtle">Upsert by route + type</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Route</th><th>Type</th><th>Base</th><th>Extra/kg</th></tr></thead><tbody>{rates.slice(0, 12).map((rate) => <tr key={rate.id}><td>{rate.originZone.name} → {rate.destinationZone.name}</td><td>{rate.orderType}</td><td>₹{Number(rate.baseRate)} / {Number(rate.baseWeightKg)}kg</td><td>₹{Number(rate.additionalRateKg)}</td></tr>)}</tbody></table></div></section><section className="card"><div className="card-head"><h2>Add or update rate</h2></div><div className="card-body"><RateCardForm zones={zones} /></div></section><section className="card"><div className="card-head"><h2>Configure COD surcharge</h2></div><div className="card-body"><CodRuleForm /></div></section></div><aside className="form"><section className="card"><div className="card-head"><h3>Service zones</h3></div><div className="card-body">{zones.map((zone) => <div key={zone.id} style={{ marginBottom: 18 }}><strong>{zone.name}</strong><div className="subtle" style={{ fontSize: 12, marginTop: 5 }}>{zone.areas.map((area) => `${area.name} (${area.postalCode})`).join(", ")}</div></div>)}</div></section><section className="card"><div className="card-head"><h3>Assign area to zone</h3></div><div className="card-body"><AreaForm zones={zones} /></div></section><section className="card"><div className="card-head"><h3>Add service zone</h3></div><div className="card-body"><ZoneForm /></div></section><section className="card"><div className="card-head"><h3>Current COD rules</h3></div><div className="card-body">{codRules.map((rule) => <div className="quote-row" style={{ color: "var(--muted)" }} key={rule.id}><span>{rule.orderType}</span><strong style={{ color: "var(--ink)" }}>₹{Number(rule.flatFee)} + {Number(rule.percentage)}%</strong></div>)}</div></section></aside></div></>;
}
