"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

type Zone = { id: string; name: string };

export function RateCardForm({ zones }: { zones: Zone[] }) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const raw = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/admin/rate-cards", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(raw) }); const body = await response.json(); setMessage(response.ok ? "Rate card saved." : body.error?.message); if (response.ok) router.refresh(); setBusy(false); }
  return <form className="form" onSubmit={submit}><div className="form-grid"><div className="field"><label>Origin zone</label><select className="select" name="originZoneId" required>{zones.map((zone) => <option key={zone.id} value={zone.id}>{zone.name}</option>)}</select></div><div className="field"><label>Destination zone</label><select className="select" name="destinationZoneId" required>{zones.map((zone) => <option key={zone.id} value={zone.id}>{zone.name}</option>)}</select></div></div><div className="form-grid"><div className="field"><label>Order type</label><select className="select" name="orderType"><option>B2C</option><option>B2B</option></select></div><div className="field"><label>Included weight (kg)</label><input className="input" name="baseWeightKg" type="number" min="0.1" step="0.1" defaultValue="1" required /></div></div><div className="form-grid"><div className="field"><label>Base rate (₹)</label><input className="input" name="baseRate" type="number" min="0" step="0.01" defaultValue="80" required /></div><div className="field"><label>Additional ₹ / kg</label><input className="input" name="additionalRateKg" type="number" min="0" step="0.01" defaultValue="25" required /></div></div>{message && <div className={message.includes("saved") ? "form-success" : "form-error"}>{message}</div>}<button className="button" disabled={busy}>{busy ? "Saving…" : "Save rate card"}</button></form>;
}

export function ZoneForm() {
  const router = useRouter(); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const raw = Object.fromEntries(new FormData(event.currentTarget)); const body = { name: raw.zoneName, areas: [{ name: raw.areaName, postalCode: raw.postalCode, latitude: Number(raw.latitude), longitude: Number(raw.longitude) }] }; const response = await fetch("/api/admin/zones", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); setMessage(response.ok ? "Zone and area created." : data.error?.message); if (response.ok) router.refresh(); setBusy(false); }
  return <form className="form" onSubmit={submit}><div className="form-grid"><div className="field"><label>Zone name</label><input className="input" name="zoneName" placeholder="Surat Central" required /></div><div className="field"><label>Area name</label><input className="input" name="areaName" placeholder="Athwa" required /></div></div><div className="field"><label>Postal code</label><input className="input" name="postalCode" required /></div><div className="form-grid"><div className="field"><label>Latitude</label><input className="input" name="latitude" type="number" step="0.000001" required /></div><div className="field"><label>Longitude</label><input className="input" name="longitude" type="number" step="0.000001" required /></div></div>{message && <div className={message.includes("created") ? "form-success" : "form-error"}>{message}</div>}<button className="button secondary" disabled={busy}>{busy ? "Creating…" : "Add zone & first area"}</button></form>;
}

export function AreaForm({ zones }: { zones: Zone[] }) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const raw = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/admin/areas", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(raw) }); const data = await response.json(); setMessage(response.ok ? "Area assigned to zone." : data.error?.message); if (response.ok) router.refresh(); setBusy(false); }
  return <form className="form" onSubmit={submit}><div className="field"><label>Zone</label><select className="select" name="zoneId">{zones.map((zone) => <option key={zone.id} value={zone.id}>{zone.name}</option>)}</select></div><div className="form-grid"><div className="field"><label>Area name</label><input className="input" name="name" required /></div><div className="field"><label>Postal code</label><input className="input" name="postalCode" required /></div></div><div className="form-grid"><div className="field"><label>Latitude</label><input className="input" name="latitude" type="number" step="0.000001" required /></div><div className="field"><label>Longitude</label><input className="input" name="longitude" type="number" step="0.000001" required /></div></div>{message && <div className={message.includes("assigned") ? "form-success" : "form-error"}>{message}</div>}<button className="button secondary" disabled={busy}>{busy ? "Assigning…" : "Assign area"}</button></form>;
}

export function CodRuleForm() {
  const router = useRouter(); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const raw = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/admin/cod-rules", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(raw) }); const data = await response.json(); setMessage(response.ok ? "COD rule saved." : data.error?.message); if (response.ok) router.refresh(); setBusy(false); }
  return <form className="form" onSubmit={submit}><div className="form-grid"><div className="field"><label>Order type</label><select className="select" name="orderType"><option>B2C</option><option>B2B</option></select></div><div className="field"><label>Flat fee (₹)</label><input className="input" name="flatFee" type="number" min="0" step="0.01" defaultValue="20" /></div></div><div className="form-grid three"><div className="field"><label>Value %</label><input className="input" name="percentage" type="number" min="0" step="0.01" defaultValue="1" /></div><div className="field"><label>Minimum</label><input className="input" name="minimumFee" type="number" min="0" defaultValue="25" /></div><div className="field"><label>Maximum</label><input className="input" name="maximumFee" type="number" min="1" defaultValue="150" /></div></div>{message && <div className={message.includes("saved") ? "form-success" : "form-error"}>{message}</div>}<button className="button secondary" disabled={busy}>{busy ? "Saving…" : "Save COD rule"}</button></form>;
}
