import { Role } from "@prisma/client";
import { notFound, redirect } from "next/navigation";
import { getSession } from "@/lib/auth";
import { db } from "@/lib/db";
import { StatusPill } from "@/components/status-pill";
import { OrderActions } from "@/components/order-actions";
import { allowedTransitions, statusLabel } from "@/lib/status-machine";

export default async function OrderDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const session = await getSession(); if (!session) redirect("/login"); const { id } = await params;
  const order = await db.order.findUnique({ where: { id }, include: { customer: true, assignedAgent: true, pickupZone: true, dropZone: true, trackingEvents: { include: { actor: { select: { name: true, role: true } } }, orderBy: { createdAt: "desc" } }, deliveryAttempts: { orderBy: { attemptNumber: "asc" } } } });
  if (!order) notFound(); if (session.role !== Role.ADMIN && order.customerId !== session.userId && order.assignedAgentId !== session.userId) notFound();
  const agents = session.role === Role.ADMIN ? await db.user.findMany({ where: { role: Role.AGENT, active: true, agentProfile: { available: true } }, select: { id: true, name: true } }) : [];
  return <><div className="page-title"><div><div style={{ display: "flex", gap: 12, alignItems: "center", marginBottom: 8 }}><span className="tracking-code">{order.trackingNumber}</span><StatusPill status={order.status} /></div><h1>Delivery details</h1><p>Created {order.createdAt.toLocaleString("en-IN")}</p></div></div><div className="two-col"><div className="form"><section className="card"><div className="card-head"><h2>Journey</h2><span className="subtle">{order.pickupZone.name} → {order.dropZone.name}</span></div><div className="card-body detail-grid"><div><div className="detail-label">Pickup</div><div className="detail-value">{order.pickupAddress}<br />{order.pickupPostalCode}</div></div><div><div className="detail-label">Drop</div><div className="detail-value">{order.dropAddress}<br />{order.dropPostalCode}</div></div><div><div className="detail-label">Customer</div><div className="detail-value">{order.customer.name}<br /><span className="subtle">{order.customer.email}</span></div></div><div><div className="detail-label">Assigned agent</div><div className="detail-value">{order.assignedAgent?.name || "Awaiting assignment"}</div></div></div></section><section className="card"><div className="card-head"><h2>Tracking timeline</h2><span className="subtle">Immutable history</span></div><div className="card-body timeline">{order.trackingEvents.map((event) => <div className="timeline-item" key={event.id}><div className="timeline-marker"><span className="timeline-dot" /><span className="timeline-line" /></div><div><div className="timeline-title">{statusLabel(event.status)}</div><div className="timeline-meta">{event.createdAt.toLocaleString("en-IN")} · {event.actor.name} ({event.actor.role.toLowerCase()})</div><div className="timeline-message">{event.message}</div></div></div>)}</div></section></div><aside className="form"><section className="quote-panel"><div className="eyebrow" style={{ color: "var(--lime)" }}>Final charge</div><div className="quote-total">₹{Number(order.totalCharge).toFixed(2)}</div><div className="quote-row"><span>Freight</span><strong>₹{Number(order.baseCharge).toFixed(2)}</strong></div><div className="quote-row"><span>COD fee</span><strong>₹{Number(order.codSurcharge).toFixed(2)}</strong></div><div className="quote-row"><span>Billable weight</span><strong>{Number(order.billableWeightKg)} kg</strong></div><div className="quote-row"><span>Order type</span><strong>{order.orderType} · {order.paymentType}</strong></div></section><OrderActions orderId={order.id} role={session.role} status={order.status} transitions={allowedTransitions(order.status, session.role)} agents={agents} /></aside></div></>;
}
